# https://docs.haskellstack.org/en/stable/travis_ci/
# run on containerized infrastructure hopefully
dist: trusty
sudo: false
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_cache:
# Do any cleanup here to avoid caching junk.

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack ghc -- --version
- stack --no-terminal build

script:
- travis_fold () {
    name=$1 && \
    shift && \
    echo -en "travis_fold:start:$name\r" && \
    $* && \
    echo -en "travis_fold:end:$name\r"
  }
- travis_fold tests       stack --no-terminal exec tests
- travis_fold transcripts stack --no-terminal exec transcripts
